version: '3' # specify docker-compose version

# Define the services/containers to be run
services:
  angular: # name of the first service
    build: client # specify the directory of the Dockerfile
    image: angular-resvit
    ports:
      - "4200:4200" # specify port forewarding
    volumes:
      - ./client:/usr/src/app

  express: #name of the second service
    build: server # specify the directory of the Dockerfile
    image: node-resvit
    ports:
      - "3000:3000" #specify ports forewarding
    volumes:
      - ./server:/usr/src/app
  postgres:
    image: postgres:11.2-alpine
    ports:
      - "5000:5000"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
