version: '3' # specify docker-compose version

# Define the services/containers to be run
services:
  angular:
    build: Front-end # specify the directory of the Dockerfile
    depends_on:
      - app
    ports:
      - "4200:4200" # specify port forewarding
    volumes:
      - ./volumes:/angular
  app:
    build: server
    depends_on:
      - postgres
    ports:
      - "3000:3000"
      - "9229:9229"

  postgres:
    image: postgres:11.2-alpine
    ports:
      - "5432:5432" 
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./volumes:/postgres
