version: "1"
services:
    frontend:
        container_name: mod_menu
        build:
            context: ./client
            dockerfile: Dockerfile
        image: menu/mod_menu_client
        ports:
            - "4200:4200"
        volumes:
            - ./client:/usr/src/app
    backend:
        container_name: mod_menu_server
        build:
            context: ./server
            dockerfile: Dockerfile
        image: menu/mod_menu_server
        ports:
            - "3000:3000"
        volumes:
            - ./server:/usr/src/app